packages:
  - apps/*
  - packages/*

catalog:
  '@better-auth/expo': ^1.4.9
  '@orpc/client': ^1.12.2
  '@orpc/openapi': ^1.12.2
  '@orpc/server': ^1.12.2
  '@orpc/tanstack-query': ^1.12.2
  '@orpc/zod': ^1.12.2
  '@polar-sh/better-auth': ^1.6.4
  '@tanstack/react-query': ^5.90.12
  better-auth: ^1.4.9
  dotenv: ^17.2.2
  next: ^16.1.4
  typescript: ^5
  zod: ^3.25.67
