packages:
  - apps/*
  - packages/*
catalog:
  dotenv: ^17.2.3
  zod: ^4.3.5
  typescript: ^5.9.3
  better-auth: ^1.4.17
  "@polar-sh/better-auth": ^1.6.4
  "@better-auth/expo": ^1.4.17
  "@orpc/client": ^1.13.4
  "@orpc/tanstack-query": ^1.13.4
  "@orpc/server": ^1.13.4
  "@orpc/zod": ^1.13.4
  "@orpc/openapi": ^1.13.4
  next: ^16.1.4
